libs =
import libs += libxtl%lib{xtl}
import libs += nlohmann-json%lib{json}
import libs += doctest%lib{doctest}

xtl_tests = test_xbase64 \
            test_xbasic_fixed_string \
            test_xcomplex \
            test_xcomplex_sequence \
            test_xclosure \
            test_xdynamic_bitset \
            test_xfunctional \
            test_xhalf_float \
            test_xhash \
            test_xhierarchy_generator \
            test_xiterator_base \
            test_xmasked_value \
            test_xmeta_utils \
            test_xmultimethods \
            test_xoptional \
            test_xsequence \
            test_xtype_traits \
            test_xplatform \
            test_xproxy_wrapper \
            test_xsystem \
            test_xvariant \
            test_xvisitor

cxx.poptions =+ "-I$out_root" "-I$src_root"
for t : $xtl_tests
{
  ./: exe{$t}: hxx{*} cxx{main} cxx{$t} $libs
}

# Test with exe linked all together
./: exe{test_xtl}: hxx{*} cxx{main} cxx{$xtl_tests} $libs

# In general compile with strict warnings checking
# Compile and link options
if ($cxx.target.system == 'win32-msvc')
{
  if($cxx.id == 'msvc')
  {
    cxx.coptions += "/EHsc" "/MP" "/bigobj"
    cxx.loptions += "/MANIFEST:NO"
  }
  elif ($cxx.id == 'msvc-clang' || $cxx.id == 'clang')
    cxx.coptions += -fms-compatibility
}
  

if($config.libxtl_tests.disable_exceptions)
{
  if($cxx.target.system == 'win32-msvc' && $cxx.id == 'msvc')
    cxx.coptions += "/EHs-c-"
  else
    cxx.coptions += -fno-exceptions
}

if($cxx.target.system != 'win32-msvc')
  cxx.libs += -pthread

